version: "3.4"
services:
    mysql:
        container_name: InClubSIT-mysql
        image: mysql:latest
        build:
            context: .
            dockerfile: ./Dockerfile.data
        ports:
            - 32769:3306
        volumes:
            - ./mount/initialise.sql:/docker-entrypoint-initdb.d/0_init.sql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: InClubSIT
            MYSQL_USER: app
            MYSQL_PASSWORD: secret
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 30s
            timeout: 30s
            retries: 5
            start_period: 30s
    app:
        container_name: InClubSIT-app
        depends_on:
            mysql:
                condition: service_healthy
        build:
            context: .
            dockerfile: ./Dockerfile.app
            # extra_hosts:
            #    - "host.docker.internal:172.17.0.1"
        #enable hot reloading of api - useful for development - disable in prod
        # entrypoint: '/start-reload.sh'
        environment:
            WORKERS_PER_CORE: 1
            TIMEOUT: 90
            SQL_HOST: mysql
            SQL_DATABASE: InClubSIT
            SQL_USER: app
            SQL_PASSWORD: secret
        ports:
            - 8001:80
        expose:
            - 8001
        links:
            - mysql:mysql
        restart: always
        volumes:
            - ./app:/code/app


volumes:
    mount: